import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import manifest from "./manifest";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta 
          name="viewport"
          content="widht=device-width, initial-scale=1.0, user-scalable=no"
        />
        <meta name="mobile-web-app-status-bar-style" content="black"/>
        <link rel="manifest" href="./manifest.js" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
